### PR TITLE
fix : postList JPA method로 정렬함

### LINKED ISSUE #21: [FEAT🛠️] 마이페이지 API 개발
## 🧐 설명!
- 마이페이지 API 개발합니다.
 

## ✔ 해야할 일! 
- 마이페이지 api 개발

### PR DESCRIPTION
**Pull request by kjy-asl**
## PR Type
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other... Please describe:

## Related Issue
- #21 

## Work Description
- postlist jpa 메서드로 정렬

## PR Point

close #21

### CODE REVIEW

File: src/main/java/com/blow/server/api/repository/PostRepository.java [hunk 1]
```diff
@@ -11,7 +11,7 @@
 public interface PostRepository extends JpaRepository<Post, Long> {
     Optional<Post> getPostById(Long postId);
     List<Post> findPostByCategoryOrderByCreatedAtDesc(String category);
-    List<Post> findAllByUserId(Long userId);
+    List<Post> findAllByUserIdOrderByCreatedAtDesc(Long userId);
     @Query("SELECT p FROM Post p WHERE LOWER(p.title) LIKE %:postTitleKeyword% OR LOWER(p.content) LIKE %:postContentKeyword% ORDER BY p.createdAt DESC")
```
Comment (GaHee99) [inline src/main/java/com/blow/server/api/repository/PostRepository.java:15]: 음 ! 같이 고쳐봅시다

**Review by GaHee99 — APPROVED** [review]
